language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

sudo: false

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi

script: vendor/bin/phpunit
